---
title: "Data Cleaning"
author: "Josiah Meadows"
date: "10/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fivethirtyeight)
library(janitor)
library(readxl)
library(ggthemes)
library(leaflet)
library(tigris)

```

```{r}

# Source: FL Department of State website.

# Sheet 1 (December)

fl_dec <- read_xlsx("party-affilation-by-county-09-2020.xlsx", skip = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>% 
  drop_na() %>%
  filter(county == "TOTALS")

# Sheet 2 (January)
  
fl_jan <- read_xlsx("party-affilation-by-county-09-2020.xlsx",
                    skip = 3,
                    sheet = 2) %>%
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 3 (February)

fl_feb <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 4 (March)

fl_mar <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 4) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 5 (April)

fl_apr <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 5) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 6 (May)

fl_may <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 6) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 7 (June)

fl_jun <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3, 
                    sheet = 7) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 8 (July)

fl_jul <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 8) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 9 (August)

fl_aug <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                    skip = 3,
                    sheet = 9) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Combined

combined <- bind_rows(fl_dec,
                      fl_jan,
                      fl_feb,
                      fl_mar,
                      fl_apr,
                      fl_may,
                      fl_jun,
                      fl_jul,
                      fl_aug) %>%
  
  # Reorder the months so they are not in alphabetical order.
  
  mutate(month = c("Dec.",
                   "Jan.",
                   "Feb.",
                   "Mar.",
                   "Apr.",
                   "May",
                   "June",
                   "July",
                   "Aug.")) %>%
  
  mutate(month = fct_relevel(month,
                             "Dec.",
                             "Jan.",
                             "Feb.",
                             "Mar.",
                             "Apr.",
                             "May",
                             "June",
                             "July",
                             "Aug.")) %>%
  
# Pivot
  
  pivot_longer(cols = republican:democrat, names_to = "party") %>%

# Create the plot
  
  ggplot(mapping = aes(x = month, y = value, color = party, group = party)) +
  geom_point() +
  geom_line() +
  labs(title = "Monthly Change in Florida Registration (2019-2020)",
       x = "Month",
       y = "Total Number of Registered Voters",
       caption = "Source: Florida Department of State") +
  theme_classic() +
  theme(legend.position = "right",
        text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size = 16, face = "bold"),
        plot.caption = element_text(face = "italic")) +
  scale_color_manual(values = c("dodgerblue", "lightcoral"),
                     name = "Party",
                     labels = c("Democratic", "Republican")) +
  scale_y_continuous(labels = scales::comma) +
  
# Create the vertical lines
  
  geom_vline(xintercept = "Mar.", color = "gray") +
  geom_vline(xintercept = "June", color = "gray") +
  
# Add the text to describe the lines

  geom_text(aes(x = "Mar.", label = "COVID-19 Cases Rise", y = 5000000),
            color = "gray",
            size = 3,
            angle = 90,
            vjust = 1.5) +
  geom_text(aes(x = "June", label = "Killing of George Floyd", y = 5000000),
            color = "gray",
            angle = 90,
            size = 3,
            vjust = 1.5)

combined

saveRDS(object = combined, file = "combined.rds")

```



```{r}

# Here, I look at increases by county in Florida.

fl_dec <- read_xlsx("party-affilation-by-county-09-2020.xlsx",
                        skip = 3) %>% 
  clean_names() %>%
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_jan <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 2) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_feb <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 3) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_mar <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 4) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_apr <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 5) %>% 
  clean_names() %>%
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_may <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 6) %>% 
  clean_names() %>%
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_jun <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 7) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_jul <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 8) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

fl_aug <- read_xlsx("party-affilation-by-county-09-2020.xlsx", 
                        skip = 3, sheet = 9) %>% 
  clean_names() %>% 
  mutate(county = str_to_upper(county)) %>% 
  drop_na()

combined 

combined <- full_join(fl_dec, fl_jan, by = "county", suffix = c("_dec", "_jan")) %>% 

  pivot_longer(cols = 2:11,
               names_to = "party") %>% 

# Use a str sub to extract the month to create a month column.

mutate(month = str_sub(party, -3, ), party = str_sub(party, , -5)) %>%
  ggplot(mapping = aes(x = month, y = value, group = county, color = county)) +
  geom_line() +
  geom_point() +
  facet_wrap(~ party)

  #ggplot(mapping = aes(x = month, y = value, color = county)) +
  #geom_point()
                      
                      #fl_feb,
                      #fl_mar,
                      #fl_apr,
                      #fl_may,
                      #fl_jun,
                      #fl_jul,
                      #fl_aug) %>%
  
  mutate(month = c("Dec",
                   "Jan",
                   "Feb",
                   "Mar",
                   "Apr",
                   "May",
                   "Jun",
                   "Jul",
                   "Aug")) %>%
  
  pivot_longer(cols = republican_party_of_florida:no_party_affiliation,
               names_to = "party")
  
  # Create map
 
  # Leaflet is like ggplot. AddTiles is almost like theme of ggplot. AddPolygons
  # adds county shapes/
  
  county_shapes <- counties(state = "FL", cb = TRUE)
  
  county_shapes %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~NAME)
  
  county_shapes %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~NAME)
  
  #geo_join()
  
  pal <- colorNumeric("Greens", domain = combined$values)

```

```{r}

#Testing how to read in other datasets. Read in data in the form of .txt.

fl_registrations <- read_tsv(file = "raw_data /Stats_10866_AbsProvided.txt")

```

```{r}

# This may or may not be useful for the final project.

# Now let's create a second plot displaying the voter registration data for 5
# swing states

voter_registrations <- read_csv(file = "https://raw.githubusercontent.com/fivethirtyeight/data/master/voter-registration/new-voter-registrations.csv") %>% 
  clean_names()

voter_registrations %>%
  rename(state = jurisdiction) %>%
  filter(state != "California") %>%
  filter(state != "Illinois") %>%
  filter(state != "Colorado") %>%
  filter(state != "Delaware") %>%
  filter(state != "District of Columbia") %>%
  filter(state != "Maryland") %>%
  filter(state != "Virginia") %>%
  
  mutate(month = fct_relevel(month, "Dec", "Jan", "Feb", "Mar", "Apr",
                             "May")) %>%
  
  ggplot(mapping = aes(x = month,
                       y = new_registered_voters,
                       color = state,
                       group = state)) +
  geom_line() +
            facet_wrap(~ year) +
            labs(title = "Voter Registration Levels in Swing States (2016 vs. 2020)",
                 x = "Month",
                 y = "New Registered Voters",
                 caption = "Source: FiveThirtyEight") +
  theme(legend.position = "right", 
        text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 10))
  
  geom_vline(xintercept = "Mar", color = "black")

voter_registrations

saveRDS(object = voter_registrations, file = "voter_registrations.rds")

```


```{r}

#This was my code for the previous milestone. I'll delete it once I get the hang
#of Shiny App.

state_info %>% 
  group_by(division) %>% 
  summarize(number = n()) %>% 

ggplot(mapping = aes(x = division, y = number)) +
  geom_col()

```

```{r}

#This was my code for the previous milestone

police_killings_region <- police_killings %>% 
  group_by(state) %>%
  summarize(count_by_state = n()) %>%
  rename(state_abbrev = state)

state_info <- state_info

police_killings2 <- left_join(police_killings_region, state_info, by = "state_abbrev")

saveRDS(object = police_killings2, file = "police_killings2.rds")

```
