---
title: "Data Cleaning"
author: "Josiah Meadows"
date: "12/01/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# This is my data cleaning file where I do all of the scratch work for my Shiny
# App. In this file, I create the RDS files for the Shiny App.

# Load all of the necessary libraries here.

library(tidyverse)
library(janitor)
library(readxl)
library(tigris)
library(dplyr)
library(leaflet)
library(rstanarm)
library(gtsummary)
library(broom.mixed)
library(gt)

```

```{r graph 1}

# First, I am going to create a graph that shows the total voter registration
# numbers in Florida by party.

# The excel spreadsheet I was using had multiple tabs for each month, so I had
# to load in the data for each individual tab in the spreadsheet. I cleaned
# the names, etc. See code below.

# Sheet 1 - December

fl_dec <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>% 
  drop_na() %>%
  filter(county == "TOTALS")

# Sheet 2 - January
  
fl_jan <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 2) %>%
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 3 - February

fl_feb <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 4 - March

fl_mar <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 4) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 5 - April

fl_apr <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 5) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 6 - May

fl_may <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 6) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 7 - June

fl_jun <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 7) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 8 - July

fl_jul <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 8) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 9 - August

fl_aug <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 9) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Now, after loading in the data, it's time to combine all of the separate
# datasets above into one big dataset. See the code below.

combined_fl <- bind_rows(fl_dec,
                      fl_jan,
                      fl_feb,
                      fl_mar,
                      fl_apr,
                      fl_may,
                      fl_jun,
                      fl_jul,
                      fl_aug) %>%
  
  mutate(month = c("Dec.",
                   "Jan.",
                   "Feb.",
                   "Mar.",
                   "Apr.",
                   "May",
                   "June",
                   "July",
                   "Aug.")) %>%
  
# At first, I thought I was ready to create the graph, but then I realized that
# I had to reorder the months so they are not in alphabetical order. They need
# to appear in the correct order on the x-axis. The code below does reorders the
# months.
  
  mutate(month = fct_relevel(month,
                             "Dec.",
                             "Jan.",
                             "Feb.",
                             "Mar.",
                             "Apr.",
                             "May",
                             "June",
                             "July",
                             "Aug.")) %>%

# Now I need to pivot_longer here so that I can include multiple lines in the 
# graph.
  
  pivot_longer(cols = republican:democrat, names_to = "party")

# Create the graph.
  
combined_fl %>% 

  ggplot(mapping = aes(x = month, y = value, color = party, group = party)) +
  geom_line(lwd = 0.7) +
  labs(title = "Monthly Change in Florida Registration by\nParty (2019-2020)",
       x = "Month",
       y = "Total Number of Registered Voters",
       caption = "Source: Florida Department of State (dos.myflorida.com)") +
  theme_classic() +
  theme(legend.position = "right",
        text = element_text(family = "Helvetica Neue"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold"),
        plot.caption = element_text(face = "italic")) +
  scale_color_manual(values = c("dodgerblue", "lightcoral"),
                     name = "Party",
                     labels = c("Democratic", "Republican")) +
  scale_y_continuous(labels = scales::comma) +
  
# Create the vertical lines.
  
  geom_vline(xintercept = "Mar.", color = "gray") +
  geom_vline(xintercept = "June", color = "gray") +
  
# Add the text to describe the lines.

  geom_text(aes(x = "Mar.",
                y = 5000000,
                label = "WHO DECLARES\nCOVID-19 PANDEMIC"),
            color = "gray",
            size = 3) +
  geom_text(aes(x = "June",
                y = 5000000,
                label = "KILLING OF\nGEORGE FLOYD"),
            color = "gray",
            size = 3)

combined_fl

# Finally I will save "combined_fl" as an RDS so that I can use it in the Shiny
# App.

saveRDS(object = combined_fl, file = "combined_fl.rds")

```

```{r graph 2}

# For the second graph, I am going to combine Republican, Democratic, and other
# parties into one linegraph. The steps are similar to the ones above.

# Sheet 1 - December

fl_dec <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>% 
  drop_na() %>%
  filter(county == "TOTALS")

# Sheet 2 - January
  
fl_jan <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 2) %>%
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 3 - February

fl_feb <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 3) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 4 - March

fl_mar <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 4) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 5 - April

fl_apr <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 5) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 6 - May

fl_may <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 6) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 7 - June

fl_jun <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 7) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 8 - July

fl_jul <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 8) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Sheet 9 - August

fl_aug <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 9) %>% 
  clean_names() %>%
  rename(republican = "republican_party_of_florida") %>%
  rename(democrat = "florida_democratic_party") %>%
  drop_na() %>% 
  filter(county == "TOTALS")

# Combined

combined_2 <- bind_rows(fl_dec,
                      fl_jan,
                      fl_feb,
                      fl_mar,
                      fl_apr,
                      fl_may,
                      fl_jun,
                      fl_jul,
                      fl_aug) %>%
  
  mutate(month = c("Dec.",
                   "Jan.",
                   "Feb.",
                   "Mar.",
                   "Apr.",
                   "May",
                   "June",
                   "July",
                   "Aug.")) %>%
  
# Again, I have to reorder the months so they are not in alphabetical order.
  
  mutate(month = fct_relevel(month,
                             "Dec.",
                             "Jan.",
                             "Feb.",
                             "Mar.",
                             "Apr.",
                             "May",
                             "June",
                             "July",
                             "Aug.")) %>%
  
  pivot_longer(cols = totals, names_to = "party")

# Create the plot.

combined_2 %>% 
  
  ggplot(mapping = aes(x = month, y = value, group = party)) +
  geom_line(color = "turquoise3", lwd = 0.7) +
  labs(title = "Monthly Change in Florida Registration (2019-2020)",
       x = "Month",
       y = "Total Number of Registered Voters",
       caption = "Source: Florida Department of State (dos.myflorida.com)") +
  theme_classic() +
  theme(legend.position = "right",
        text = element_text(family = "Helvetica Neue"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold"),
        plot.caption = element_text(face = "italic")) +
  scale_y_continuous(labels = scales::comma) +

# Create the vertical lines.
  
  geom_vline(xintercept = "Mar.", color = "gray") +
  geom_vline(xintercept = "June", color = "gray") +
  
# Add the text to describe the lines.

  geom_text(aes(x = "Mar.",
                y = 13650000,
                label = "WHO DECLARES\nCOVID-19 PANDEMIC"),
            color = "gray",
            size = 3) +
  geom_text(aes(x = "June",
                y = 13650000,
                label = "KILLING OF\nGEORGE FLOYD"),
            color = "gray",
            size = 3)
  
combined_2

# Let's also save this RDS for the Shiny App.

saveRDS(object = combined_2, file = "combined_2.rds")

```


```{r map 1, warning=FALSE}

# Note: I kept getting a warning when I ran this code chunk. My TF said I didn't
# have to worry about this particular warning since I am using using Leaflet,
# which is outside the scope of the Gov 50 course. I simply used warning=FALSE
# to hide it. In all other instances when I got warnings, I changed the code to
# address them.

# Here, I look at increases by county in Florida.

fl_dec <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3) %>% 
  clean_names() %>%
  mutate(county = str_to_title(county)) %>% 
  drop_na()

fl_jan <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 2) %>% 
  clean_names() %>% 
  drop_na()

fl_feb <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 3) %>% 
  clean_names() %>% 
  drop_na()

fl_mar <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 4) %>% 
  clean_names() %>% 
  drop_na()

fl_apr <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 5) %>% 
  clean_names() %>%
  drop_na()

fl_may <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 6) %>% 
  clean_names() %>%
  drop_na()

fl_jun <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 7) %>% 
  clean_names() %>% 
  drop_na()

fl_jul <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 8) %>% 
  clean_names() %>% 
  drop_na()

fl_aug <- read_xlsx("raw_data /fl_counties.xlsx", skip = 3, sheet = 9) %>% 
  clean_names() %>% 
  drop_na()

# This is a long, intricate section where I combine all of the months into
# a single tibble that I can easily use in my Shiny App. The reason I did this
# step was so that I could easily create the drop-down list in the Shiny App. In
# each instance, I use str_sub to extract the month to create a month column.

# Combine January and February.

combined_3 <- full_join(fl_jan,
                      fl_feb,
                      by = "county",
                      suffix = c("_jan", "_feb")) %>% 

  pivot_longer(cols = 2:11,
               names_to = "party") %>% 

# Combine March and April.

mutate(month = str_sub(party, -3, ), party = str_sub(party, , -5))

combined_4 <- full_join(fl_mar,
                      fl_apr,
                      by = "county",
                      suffix = c("_mar", "_apr")) %>% 

  pivot_longer(cols = 2:11,
               names_to = "party") %>% 

mutate(month = str_sub(party, -3, ), party = str_sub(party, , -5))

# Combined_Intermediate includes half of the months for the drop-down list.

combined_intermediate <- bind_rows(combined_3, combined_4)

combined_intermediate %>%
  filter(month == "jan", party == "florida_democratic_party")

# I now save this code in an RDS to use in the Shiny App.

saveRDS(object = combined_intermediate, file = "combined_intermediate.RDS")

# Let's do all of the months so that we have a full drop-down list.

# Combine May and June.

combined_5 <- full_join(fl_may,
                      fl_jun,
                      by = "county",
                      suffix = c("_may", "_jun")) %>% 

  pivot_longer(cols = 2:11,
               names_to = "party") %>% 

# Combine July and August.

mutate(month = str_sub(party, -3, ), party = str_sub(party, , -5))

combined_6 <- full_join(fl_jul,
                      fl_aug,
                      by = "county",
                      suffix = c("_jul", "_aug")) %>% 

  pivot_longer(cols = 2:11,
               names_to = "party") %>% 

mutate(month = str_sub(party, -3, ), party = str_sub(party, , -5))

# The combined_full object contains all the months. Now we are ready to use it
# for the drop-down list.

# One small issue that I found: In one dataset, "DeSoto" had a capital "S", in
# another, it did not. I resolved this small issue by changing all to "DeSoto".
# Now everything merges smoothly. I was wondering why that one county was blank
# in my map. This shows the importance of cleaning the data!

combined_full <- bind_rows(combined_3,
                           combined_4,
                           combined_5,
                           combined_6) %>% 
  mutate(county = str_replace_all(county, "Desoto", "DeSoto"))


# Finally, I save this to an RDS file so that I can use it in my Shiny App.

saveRDS(object = combined_full, file = "combined_full.RDS")


# Create map.
 
# Leaflet is like ggplot. AddTiles is almost like the theme of ggplot.
# AddPolygons adds county shapes. 12 is the number for the state of Florida.
  
  county_shapes <- counties(state = "12", cb = TRUE)
  
  county_shapes %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~NAME)
  
sb_county <- fl_jan <- read_xlsx("raw_data /fl_counties.xlsx", 
                        skip = 3, sheet = 2) %>% 
  clean_names() %>%
  drop_na()

# Using the geo_join() command, I combined the the registration data with
# the county shapes.

counties_merged_sb <- geo_join(county_shapes, sb_county, "NAME", "county")

# This is where I specify the specific shades of green and the numbers
# to which they correspond.

pal <- colorBin("Greens", bins = c(1000, 5000, 10000, 100000, 200000, Inf))

  counties_merged_sb %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~paste(totals, "Voter Registrations"),
                fillColor = ~pal(totals))
  
# This creates the nice pop-up feature which allows the user to see the
# information.
  
  popup_sb <- paste0("County: ", as.character(counties_merged_sb$NAME),
                     "\nTotal Registrations: ", as.character(counties_merged_sb$totals))
  
  leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    setView(-82, 28, zoom = 6) %>% 
    addPolygons(data = counties_merged_sb,
                fillColor = ~pal(counties_merged_sb$totals),
                fillOpacity = 0.7,
                weight = 0.2,
                smoothFactor = 0.2,
                highlight = highlightOptions(
                  weight = 5,
                  color = "#666",
                  fillOpacity = 0.7,
                  bringToFront = TRUE),
                label = popup_sb,
                labelOptions = labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>% 
    addLegend(pal = pal,
              values = counties_merged_sb$total,
              position = "bottomright",
              title = "Total Registrations")

```

```{r leaflet 2, warning=FALSE}

# Note: I kept getting a warning when I ran this code chunk. My TF said I didn't
# have to worry about this particular warning since I am using using Leaflet,
# which is outside the scope of the Gov 50 course. I simply used warning=FALSE
# to hide it. In all other instances when I got warnings, I changed the code to
# address them.

# Now let's do the same for the COVID data.

covid <- read_csv(file = "raw_data /us-counties.csv") %>% 

  clean_names() %>% 
  filter(state == "Florida") %>% 
  mutate(month = str_sub(date, 6, 7)) %>% 
  mutate(month = as.numeric(month)) %>% 
  group_by(month, county) %>% 
  summarize(total_cases = sum(cases),
            total_deaths = sum(deaths), .groups = "drop")

# I save this code in an RDS file so that I can use it in my Shiny App.

saveRDS(object = covid, file = "covid.RDS")

# Map

# 12 is the number for the state of Florida.

county_shapes <- counties(state = "12", cb = TRUE)
  
  county_shapes %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~NAME)
  
  sb_county2 <- covid %>% 
    clean_names() %>%
    drop_na()
  
# Using the geo_join() command, I combined the the registration data with
# the county shapes.
    
counties_merged_sb2 <- geo_join(county_shapes, sb_county2, "NAME", "county")

# Specify the shades of red and the numbers to which they correspond.

pal <- colorBin("Reds", bins = c(1000, 5000, 10000, 100000, 200000, Inf))

  counties_merged_sb2 %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~paste(total_cases, "Cases"),
                fillColor = ~pal(total_cases))
  
# This creates the nice pop-up feature which allows the user to see the
# information.
  
  popup_sb2 <- paste0("New Cases: ", as.character(counties_merged_sb2$totals))
  
  # Now create the map. Almost everything below affects the style and display
  # of the map.
  
    leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    setView(-82, 28, zoom = 6) %>% 
    addPolygons(data = counties_merged_sb2,
                fillColor = ~pal(counties_merged_sb2$total_cases),
                fillOpacity = 0.7,
                weight = 0.2,
                smoothFactor = 0.2,
                highlight = highlightOptions(
                  weight = 5,
                  color = "#666",
                  fillOpacity = 0.7,
                  bringToFront = TRUE),
                label = popup_sb2,
                labelOptions = labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>% 
    addLegend(pal = pal,
              values = counties_merged_sb2$total_cases,
              position = "bottomright",
              title = "Total Cases")
```

```{r leaflet 3, warning=FALSE}

# Note: I kept getting a warning when I ran this code chunk. My TF said I didn't
# have to worry about this particular warning since I am using using Leaflet,
# which is outside the scope of the Gov 50 course. I simply used warning=FALSE
# to hide it. In all other instances when I got warnings, I changed the code to
# address them.

# Now, I want to include unemployment data, too. Let's read in the data in do
# some cleaning.

jobs <- read_xlsx("raw_data /LAUS2020.xlsx", skip = 4) %>% 
  clean_names() %>%
    rename(county = area, 
         month = mo,
         employed = emp,
         unemployed = unemp) %>%
  mutate(county = str_remove_all(county, " County")) %>% 
  group_by(month, county) %>%
  summarize(total_unemp = sum(unemployed),
            total_emp = sum(employed), 
            .groups = "drop")
  
# Save my RDS afterwards as always.

saveRDS(object = jobs, file = "jobs.RDS")

# Map

county_shapes <- counties(state = "FL", cb = TRUE)
  
  county_shapes %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~NAME)
  
  sb_county3 <- jobs %>% 
    clean_names() %>%
    drop_na()
  
# Using the geo_join() command, I combined the the registration data with
# the county shapes.
    
counties_merged_sb3 <- geo_join(county_shapes, sb_county3, "NAME", "county")

# Here, I specify the shades of orange and the numbers to which they correspond.

pal <- colorBin("Oranges", bins = c(1000, 5000, 10000, 100000, 200000, Inf))

  counties_merged_sb3 %>% 
    leaflet() %>% 
    addTiles() %>% 
    addPolygons(popup = ~paste(total_unemp, "Unemployed"),
                fillColor = ~pal(total_unemp))
  
# This creates the nice pop-up feature which allows the user to see the
# information.
  
  popup_sb3 <- paste0("Total Unemployed: ",
                      as.character(counties_merged_sb3$totals))
  
    leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    setView(-82, 28, zoom = 6) %>% 
    addPolygons(data = counties_merged_sb3,
                fillColor = ~pal(counties_merged_sb3$total_unemp),
                fillOpacity = 0.7,
                weight = 0.2,
                smoothFactor = 0.2,
                highlight = highlightOptions(
                  weight = 5,
                  color = "#666",
                  fillOpacity = 0.7,
                  bringToFront = TRUE),
                label = popup_sb3,
                labelOptions = labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>% 
    addLegend(pal = pal,
              values = counties_merged_sb3$total_unemp,
              position = "bottomright",
              title = "Total Unemployed")


```

```{r model}

# Finally, I create my statistical model in this code chunk.

# Before creating the model, however, I need to reformat the columns in one
# datasets so it matches with the same column in other. Otherwise, I won't be
# able to join them.

voters <- combined_full %>% 
  mutate(month = str_replace_all(month, "jan", "1")) %>% 
  mutate(month = str_replace_all(month, "feb", "2")) %>% 
  mutate(month = str_replace_all(month, "mar", "3")) %>% 
  mutate(month = str_replace_all(month, "apr", "4")) %>% 
  mutate(month = str_replace_all(month, "may", "5")) %>% 
  mutate(month = str_replace_all(month, "jun", "6")) %>% 
  mutate(month = str_replace_all(month, "jul", "7")) %>% 
  mutate(month = str_replace_all(month, "aug", "8")) %>% 
  mutate(month = as.numeric(month)) %>% 
  rename(registrations = value)

# I have to join twice. For a while, I was trying to join 3 datasets, but 
# inner_join() only has x and y!

new_obs <- inner_join(voters, jobs, by = c("county", "month"))
new_obs2 <- inner_join(new_obs, covid, by = c("county", "month"))

# Now let's go ahead and create the stan_glm().

fit_obj<- stan_glm(data = new_obs2,
         formula = registrations ~ total_unemp + total_deaths + total_cases,
         family = gaussian(),
         refresh = 0)

print(fit_obj, digits = 4)

table <- tbl_regression(fit_obj, intercept = TRUE)

# Save the RDS for Shiny.

saveRDS(object = table, file = "table.rds")

```

